config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  devise_for :customers, controllers: { registrations: 'registrations' }, skip: [:sessions]
  as :customer do
    get 'sign_in', to: 'devise/sessions#new', as: :new_customer_session
    post 'sign_in', to: 'devise/sessions#create', as: :customer_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_customer_session
  end
  
  resources :customers
  resources :orders do
    collection do
      get 'past_orders'
    end

    member do
      get 'new_payment'
      post 'create_payment'
    end
  end
  resources :products
  resources :products_carts
  resource :cart, only: [:show] do
    post 'add/:id', to: 'carts#add', as: 'add_to'
    delete 'remove/:id', to: 'carts#remove', as: 'remove_from'
    patch 'update/:id', to: 'carts#update', as: 'update'
  end

  resources :categories

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Verbose Volley - Volleyball Equipment, Gear, and Accessories">
  <title>Verbose Volley</title>
  
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %> 
</head>

<body>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Products', products_path %></li>
      <li><%= link_to 'Categories', categories_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'Cart', cart_path %></li> <!-- Add Cart link here -->
      <% if customer_signed_in? %>
        <li><%= link_to 'My Account', customer_path(current_customer) %></li>
        <li><%= link_to "Sign Out", destroy_customer_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_customer_session_path %></li>
        <li><%= link_to 'Sign Up', new_customer_registration_path %></li>
      <% end %>
    </ul>
  </nav>

  <main>
    <%= yield %> <!-- This renders the page content -->
  </main>

  <footer>
    <p>VerboseVolley</p>
  </footer>
</body>
</html>