config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  devise_for :customers, controllers: { registrations: 'registrations' }, skip: [:sessions]
  as :customer do
    get 'sign_in', to: 'devise/sessions#new', as: :new_customer_session
    post 'sign_in', to: 'devise/sessions#create', as: :customer_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_customer_session
  end
  
  resources :customers
  resources :orders do
    collection do
      get 'past_orders'
    end

    member do
      get 'new_payment'
      post 'create_payment'
    end
  end
  resources :products
  resources :products_carts
  resource :cart, only: [:show] do
    post 'add/:id', to: 'carts#add', as: 'add_to'
    delete 'remove/:id', to: 'carts#remove', as: 'remove_from'
    patch 'update/:id', to: 'carts#update', as: 'update'
  end

  resources :categories

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root 'pages#home'
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable

  belongs_to :province, optional: true
  has_one :cart, dependent: :destroy
  has_many :orders

  validates :customer_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d+\z/, message: "only allows numbers" }
  validates :address, presence: true

  after_create :create_cart

  def self.ransackable_associations(auth_object = nil)
    ["orders"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "customer_name", "email", "id", "password", "phone_number", "address", "province_id", "updated_at"]
  end

  private

  def create_cart
    Cart.create!(customer: self)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_path, status: :see_other, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:customer_name, :email, :password, :phone_number)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/shared/_customer_form.html.erb
<!-- app/views/shared/_customer_form.html.erb -->
<div class="field">
  <%= f.label :customer_name %><br />
  <%= f.text_field :customer_name %>
</div>

<div class="field">
  <%= f.label :phone_number %><br />
  <%= f.telephone_field :phone_number %>
</div>

app/views/customers/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: object.errors.count,
                 resource: object.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_customer_registration_path %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_customer_password_path %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_customer_confirmation_path %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_customer_unlock_path %><br />
<% end %>